const SEED_ID = "xenon-ai-destination-demo-v1";

const profiles = [
    { siteKey: "petra", name: "Petra", aliases: ["Petra Visitor Centre", "Petra, Jordan"], environmentTags: ["sandy", "hot", "strenuous", "long-walks"], accessibilityTags: ["uneven-ground"], climateNotes: "An exposed dry site; actual temperature is determined from the dated forecast.", terrainNotes: "Sandstone paths, uneven ground, and potentially long walking distances." },
    { siteKey: "jerash", name: "Jerash", aliases: ["Jerash Visitor Centre", "Jerash, Jordan"], environmentTags: ["hot", "long-walks"], accessibilityTags: ["uneven-ground"], climateNotes: "An exposed archaeological site; use the dated forecast for temperature decisions.", terrainNotes: "Stone streets and archaeological paths with moderate walking." },
    { siteKey: "amman", name: "Amman", aliases: ["Roman Theatre, Amman", "downtown Amman"], environmentTags: ["crowded", "hilly"], accessibilityTags: ["urban", "stairs"], climateNotes: "Urban conditions vary by season; use the dated forecast.", terrainNotes: "Hilly urban streets with some stairs and paved walking." },
    { siteKey: "wadi-rum", name: "Wadi Rum", aliases: ["Wadi Rum Village", "Wadi Rum, Jordan"], environmentTags: ["sandy", "hot", "strenuous"], accessibilityTags: ["off-road"], climateNotes: "Dry desert exposure; use the dated forecast for heat decisions.", terrainNotes: "Sand, rock, and off-road terrain." },
    { siteKey: "dead-sea", name: "Dead Sea", aliases: ["Sweimeh", "Dead Sea Road"], environmentTags: ["hot", "water"], accessibilityTags: ["resort"], climateNotes: "Low-elevation area that can be hot; humidity varies and should be checked against dated observations when available.", terrainNotes: "Resort paths and shoreline access." },
    { siteKey: "ajloun", name: "Ajloun", aliases: ["Ajloun Forest Reserve", "Ajloun Castle"], environmentTags: ["hilly"], accessibilityTags: ["forest-trail"], climateNotes: "Forested upland setting; use the dated forecast for current conditions.", terrainNotes: "Forest trails and hills; route difficulty depends on the package itinerary." },
    { siteKey: "madaba", name: "Madaba", aliases: ["St George's Church", "Madaba Map"], environmentTags: ["urban"], accessibilityTags: ["paved"], climateNotes: "Urban inland setting; use the dated forecast.", terrainNotes: "Mostly paved urban walking with indoor workshop options." },
    { siteKey: "umm-qais", name: "Umm Qais", aliases: ["Gadara", "Umm Qais Archaeological Site"], environmentTags: ["hilly", "long-walks"], accessibilityTags: ["uneven-ground"], climateNotes: "Northern upland location; use the dated forecast.", terrainNotes: "Stone ruins, slopes, and uneven archaeological paths." },
    { siteKey: "aqaba", name: "Aqaba", aliases: ["Aqaba Marine Park", "Aqaba, Jordan"], environmentTags: ["humid", "hot", "water"], accessibilityTags: ["marine"], climateNotes: "Coastal heat and humidity can be relevant; use the dated forecast.", terrainNotes: "Beach, boat, and marine-access environments." },
    { siteKey: "dana", name: "Dana", aliases: ["Dana Village", "Dana Reserve"], environmentTags: ["hilly", "strenuous"], accessibilityTags: ["village-trail"], climateNotes: "Elevated reserve conditions vary; use the dated forecast.", terrainNotes: "Village slopes and reserve trails with variable difficulty." }
];

module.exports = { SEED_ID, profiles };
