const SEED_ID = "xenon-ai-demo-v1";

const packages = [
    { key: "petra-family", name: "Petra Family Heritage Day", description: "A family-friendly cultural journey through Petra, Jordan with a local heritage guide.", price: 65, type: "cultural", tags: ["Jordan", "Petra", "family", "heritage"], seats: 18, point: "Petra Visitor Centre, Jordan", lat: 30.3285, lng: 35.4444, activities: "Walk the Siq, visit the Treasury, and join a child-friendly Nabataean history session." },
    { key: "jerash-roman", name: "Jerash Roman History Walk", description: "Explore the Roman ruins of Jerash, Jordan in a relaxed historical tour.", price: 38, type: "historical", tags: ["Jordan", "Jerash", "Roman", "culture"], seats: 24, point: "Jerash Visitor Centre, Jordan", lat: 32.2744, lng: 35.8908, activities: "Visit Hadrian's Arch, the Oval Plaza, theatres, and the colonnaded street." },
    { key: "amman-culture", name: "Amman Culture and Food Trail", description: "Discover downtown Amman, Jordan through museums, markets, cuisine, and local stories.", price: 42, type: "cultural", tags: ["Jordan", "Amman", "food", "museum", "family"], seats: 15, point: "Roman Theatre, Amman, Jordan", lat: 31.9516, lng: 35.9393, activities: "Tour the Roman Theatre, local souqs, cultural galleries, and traditional food stops." },
    { key: "wadi-rum", name: "Wadi Rum Desert Adventure", description: "A guided desert adventure in Wadi Rum, Jordan with jeep touring and stargazing.", price: 110, type: "adventure", tags: ["Jordan", "Wadi Rum", "desert", "stargazing"], seats: 12, point: "Wadi Rum Village, Jordan", lat: 29.5764, lng: 35.4195, activities: "Jeep safari, sandstone viewpoints, Bedouin dinner, and guided stargazing." },
    { key: "dead-sea", name: "Dead Sea Wellness Escape", description: "A relaxing wellness day at the Dead Sea in Jordan with spa access.", price: 95, type: "relaxation", tags: ["Jordan", "Dead Sea", "spa", "wellness"], seats: 20, point: "Dead Sea Road, Sweimeh, Jordan", lat: 31.5590, lng: 35.4732, activities: "Dead Sea floating, mineral mud experience, lunch, and resort spa time." },
    { key: "ajloun", name: "Ajloun Forest Family Hike", description: "A mild-weather family nature experience in Ajloun, Jordan with castle history.", price: 48, type: "family", tags: ["Jordan", "Ajloun", "family", "forest", "cool"], seats: 16, point: "Ajloun Forest Reserve, Jordan", lat: 32.3326, lng: 35.7517, activities: "Easy forest trail, picnic, wildlife interpretation, and Ajloun Castle visit." },
    { key: "madaba", name: "Madaba Mosaic Workshop", description: "A hands-on cultural package in Madaba, Jordan focused on mosaics and local history.", price: 52, type: "cultural", tags: ["Jordan", "Madaba", "mosaic", "children", "art"], seats: 14, point: "St George's Church, Madaba, Jordan", lat: 31.7196, lng: 35.7933, activities: "View the Madaba Map, meet artisans, and create a small family mosaic." },
    { key: "umm-qais", name: "Umm Qais Northern Heritage", description: "Historical ruins, village culture, and cooler northern views in Umm Qais, Jordan.", price: 58, type: "historical", tags: ["Jordan", "Umm Qais", "heritage", "cool"], seats: 18, point: "Umm Qais Archaeological Site, Jordan", lat: 32.6538, lng: 35.6846, activities: "Explore Gadara ruins, Ottoman village houses, and panoramic northern viewpoints." },
    { key: "aqaba", name: "Aqaba Family Sea Day", description: "A family-focused Red Sea experience in Aqaba, Jordan with gentle water activities.", price: 85, type: "family", tags: ["Jordan", "Aqaba", "family", "sea", "snorkeling"], seats: 22, point: "Aqaba Marine Park, Jordan", lat: 29.4267, lng: 34.9784, activities: "Glass-bottom boat, beginner snorkeling, beach lunch, and marine-life education." },
    { key: "dana", name: "Dana Village Eco Retreat", description: "A quiet cultural and nature retreat in Dana, Jordan with village hospitality.", price: 125, type: "relaxation", tags: ["Jordan", "Dana", "eco", "village", "cool"], seats: 10, point: "Dana Village, Jordan", lat: 30.6268, lng: 35.4972, activities: "Village walk, local meal, sunset viewpoint, and gentle reserve trail." }
];

module.exports = { SEED_ID, packages };
