export const ROUTES = {
  HOME: '/home',
  LOGIN: '/login',
  TRAVELLER_REGISTER: '/register/traveller',
  VENDOR_REGISTER: '/register/vendor',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  MY_REVIEWS: '/reviews',
  PACKAGES: '/packages',
  BOOKINGS: '/bookings',
  VENDOR: '/vendor',
  VENDOR_PACKAGES: '/vendor/packages',
  VENDOR_PACKAGE_CREATE: '/vendor/packages/new',
  VENDOR_BOOKINGS: '/vendor/bookings',
  VENDOR_ANALYTICS: '/vendor/analytics',
  VENDOR_PROFILE: '/vendor/profile',
  VENDOR_SETTINGS: '/vendor/settings',
  ADMIN: '/admin',
  ADMIN_VENDORS: '/admin/vendors',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_REVIEWS: '/admin/reviews',
  NOT_FOUND: '*',
}
