export const ROUTES = {
  LANDING: '/',
  HOME: '/home',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VENDOR_REGISTER: '/register/vendor',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  VENDOR: '/vendor',
  VENDOR_PACKAGES: '/vendor/packages',
  VENDOR_PACKAGE_CREATE: '/vendor/packages/new',
  VENDOR_BOOKINGS: '/vendor/bookings',
  VENDOR_ANALYTICS: '/vendor/analytics',
  VENDOR_PROFILE: '/vendor/profile',
  VENDOR_SETTINGS: '/vendor/settings',
  VENDOR_STAFF: '/vendor/staff',
  VENDOR_COMPLAINTS: '/vendor/complaints',
  VENDOR_REVIEWS: '/vendor/reviews',
  VENDOR_NOTIFICATIONS: '/vendor/notifications',
  VENDOR_PAYMENTS: '/vendor/payments',
  ADMIN: '/admin',
  NOT_FOUND: '*',
}
