const AppError = require('./AppError'); 
const { checkRole } = require('./checkvalidete');
/**
 * @param {Object} req 
 * @param {String} userRole 
 * @returns {Object} 
 */
exports.extractAndValidateSessionData = (req, userRole) => {
    const ip_address = req.headers['x-forwarded-for'] || req.ip || req.connection.remoteAddress || 'Unknown IP';
    
    // device_id should ideally be generated by frontend and sent in headers or body
    const device_id = req.headers['x-device-id'] || req.body.device_id || 'unknown-device-id';

    let providedDeviceType = req.body.device_type || req.headers['x-client-type'];
    if (providedDeviceType === 'tablet') providedDeviceType = 'mobile';

    const isMobile = providedDeviceType === 'mobile';
    
    const device_type = isMobile ? 'mobile' : 'web';

    return {
        ip_address,
        device_type,
        device_id
    };
};

exports.getDeviceType = (val) => val || "web";
exports.calculateSessionExpiry = (val) => val || new Date(Date.now() + 30 * 24 * 60 * 60 * 1000);
exports.getClientIp = (val) => val || "127.0.0.1";
exports.getDeviceId = (val) => val || "unknown-device-id";
exports.getRole = (val) => val || "user";
exports.getIsActive = (val) => val !== undefined ? val : true;
exports.getSessionStatus = (val) => val || "active";
exports.getFamilyId = (val) => val || "unknown-family-id";
